version: "3.9"

services:
  ## Keystone ###########################################
  keystone:
    image: poseidoncmms:0.1.0
    build:
      context: ./keystone
    depends_on:
        - "db"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - NODE_ENV=development
      - SESSION_SECRET=${SESSION_SECRET}
      - M2M_API_KEY=${M2M_API_KEY}
      - CORS_FRONTEND_URL=http://localhost:8080
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - /home/node/public

  ### PostgreSQL ##############################################
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  frontend:
  backend:
