version: "3.9"

services:
  ## Keystone ###########################################
  keystone:
    build:
      dockerfile: ./keystone/Dockerfile
      context: .
    depends_on:
        - "db"
    environment:
      - DATABASE_URL=postgres://poseidonuser:poseidonpassword@db:5432/poseidon
      - NODE_ENV=${NODE_ENV}
      - SESSION_SECRET=${SESSION_SECRET}
      - M2M_API_KEY=${M2M_API_KEY}
      - CORS_FRONTEND_URL=${CORS_FRONTEND_URL}
      - PORT=${PORT}
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - /home/node/public

  ## PostgreSQL ##############################################
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=poseidon
      - POSTGRES_USER=poseidonuser
      - POSTGRES_PASSWORD=poseidonpassword
    networks:
      - backend
    ports:
      - 5432:5432

networks:
  frontend:
  backend:
